const Permission = {
    CREATE_USER: "CREATE_USER",
    READ_SINGLE_USER: "READ_SINGLE_USER",
    READ_USERS: "READ_USERS",
    UPDATE_USER: "UPDATE_USER",
    DELETE_USER: "DELETE_USER",
    DISABLE_USER: "DISABLE_USER",
    READ_PROFILE: "READ_PROFILE",
    UPDATE_PROFILE: "UPDATE_PROFILE",
    READ_SINGLE_PROFILE: "READ_SINGLE_PROFILE",
    READ_LITE_PROFILE: "READ_LITE_PROFILE",
    UPDATE_USERS_PASSWORD: "UPDATE_USERS_PASSWORD",
    UPDATE_PASSWORD: "UPDATE_PASSWORD",

  
};

export default Permission;
